apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: sportstix
  labels:
    app.kubernetes.io/part-of: sportstix
    app.kubernetes.io/component: gateway
data:
  SERVER_PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: sportstix
  labels:
    app.kubernetes.io/part-of: sportstix
    app.kubernetes.io/component: auth
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.sportstix.svc.cluster.local:5432/sportstix_auth"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  namespace: sportstix
  labels:
    app.kubernetes.io/part-of: sportstix
    app.kubernetes.io/component: game
data:
  SERVER_PORT: "8082"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.sportstix.svc.cluster.local:5432/sportstix_game"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: queue-config
  namespace: sportstix
  labels:
    app.kubernetes.io/part-of: sportstix
    app.kubernetes.io/component: queue
data:
  SERVER_PORT: "8083"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
  namespace: sportstix
  labels:
    app.kubernetes.io/part-of: sportstix
    app.kubernetes.io/component: booking
data:
  SERVER_PORT: "8084"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.sportstix.svc.cluster.local:5432/sportstix_booking"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: sportstix
  labels:
    app.kubernetes.io/part-of: sportstix
    app.kubernetes.io/component: payment
data:
  SERVER_PORT: "8085"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.sportstix.svc.cluster.local:5432/sportstix_payment"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
  namespace: sportstix
  labels:
    app.kubernetes.io/part-of: sportstix
    app.kubernetes.io/component: admin
data:
  SERVER_PORT: "8086"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.sportstix.svc.cluster.local:5432/sportstix_admin"
