apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-external-secret
  namespace: sportstix
  labels:
    app.kubernetes.io/part-of: sportstix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: sportstix/db-credentials
        property: password
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: sportstix/db-credentials
        property: password
