apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-external-secret
  namespace: sportstix
  labels:
    app.kubernetes.io/part-of: sportstix
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: sportstix/jwt-secret
        property: private-key
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: sportstix/jwt-secret
        property: public-key
    - secretKey: JWT_KID
      remoteRef:
        key: sportstix/jwt-secret
        property: kid
